### PR TITLE
Adding Raw Data Files

### PR DESCRIPTION
**Pull request by morganjacobus**
This commit adds the raw bus stop census responses, the anonymyzation code, and the email key. Some files are ignored for privacy reasons. Also removing bus_stop_scorecard script because it is not relevant at this time.

### CODE REVIEW

**Comment by QYAN24** [comment]
How much are these columns used?
- `Curbside Boarding`
- `Another HUGE inconvenience`

Do we need the following trailing columns?
- `Resent-From`
- `To`
- `Date`
- `Subject`
- `Cc`
- `From`

**Review by QYAN24 — COMMENTED** [review]
See https://github.com/martaarmy-barracks/busstopcensus/pull/3#issuecomment-757536841

**Comment by morganjacobus** [comment]
I need help from Sid to determine what those columns are used for. They are artifacts from the various data pulls we've performed.

**Review by QYAN24 — APPROVED** [review]
Apologies for not getting to this earlier.

**Pull request merged**
